### ISSUE TITLE
How to add workflow app to direktiv

### ISSUE THREAD

**Issue by woniupapa** [vorteil/direktiv-apps#3]
### Just ask what you want to know about vorteil
Dear all,
   I used "sh build-local.sh redis" to build app and want to add workflow for direktiv.

1.docker run --privileged -p 8080:80 -ti vorteil/direktiv-kube (done,It works)
2.direkcli namespaces create demo (done,It works)
3.create redis.yml file (done)
![image](https://user-images.githubusercontent.com/2526267/122505804-a843fb80-d02f-11eb-94e6-607cf7ef42b6.png)
4./direkcli workflows create demo redis.yml (failed)
![image](https://user-images.githubusercontent.com/2526267/122506046-1e486280-d030-11eb-8c72-603b8ff606f9.png)

Help me!!!

**Comment by jamesjmurtagh** [comment]
Hi @woniupapa !

It looks like there are a couple of issues at play here.
1. `function` should be `functions`
2. a recent push to direktiv is imposing different regex restrictions on the function `id` fields; I will work on fixing this so that it will continue to support values that match the format shown in your workflow (`redis-obj` on line 3 and line 7). 

For now, if you make the following changes to your workflow you should be able to proceed:

```yml
id: redis
functions:
- id: redisOp
  image: vorteil/redis:v2
description: "Gets a key value or set an array of KEY=VALUE strings"
states:
- id: redis-obj
  type: action
  action:
    function: redisOp
    input: '
      {
        "method": "get",
        "addr": "localhost:6379",
        "password": "",
        "db": 0,
        "values": "TEST"
      } 
    '
```

**Note:** The `input` field should contain either the `GET` or `SET` objects that are provided on the [README](https://github.com/vorteil/direktiv-apps/tree/master/redis) - ensuring that the fields match your Redis environment. We will update the example workflow in README.md to reflect this.
